### ISSUE TITLE
i got this error 

### ISSUE THREAD

**Issue by Hamzaalkhaldi** [JetP1ane/Callisto#6]
Traceback (most recent call last):
  File "/home/kali/tools/Callisto/callisto.py", line 193, in <module>
    Callisto().controller()
  File "/home/kali/tools/Callisto/callisto.py", line 65, in controller
    f = open("output.c", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'output.c'

**Comment by p0nymc1** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'semgrep'

**Comment by RandomSignals** [comment]
> Traceback (most recent call last): File "/home/kali/tools/Callisto/callisto.py", line 193, in Callisto().controller() File "/home/kali/tools/Callisto/callisto.py", line 65, in controller f = open("output.c", "r") FileNotFoundError: [Errno 2] No such file or directory: 'output.c'

Same error on my side
